name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install
        run: npm install

      - name: Start eslint
        run: npx eslint ./src/. --ext .ts

      - name: Start stylelint
        run: npx stylelint src/*/*.scss

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: .


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download files
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: .

      - name: Send files to tachka
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*"
          target: "/home/ubuntu/planexa/frontend/"

      - name: Start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: cd /home/ubuntu/planexa/frontend/;npm run install;npm run onlyBuild;
