name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: .

      - name: Download files
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: .

      - name: Send files to tachka
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*"
          target: "/home/ubuntu/planexa/frontend/"

      - name: Start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: cd /home/ubuntu/planexa/frontend/;npm run install;npm run onlyBuild;
